---
- name: Install Services And Managing Hosts
  hosts: proxy
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  remote_user: root
  
  tasks:
  - name: Install Repository
    yum: >
      name=http://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm
      state=present
      
  - name: Install Socks-Proxy Server
    yum: >
      update_cache=yes
      enablerepo=gf-plus
      name=dante-server
      state=latest

  - name: Make Dir for PID-file
    file:
      path: /var/run/sockd
      state: directory
      mode: 0755
      
  - name: Make backup of sockd.conf
    command: mv /etc/sockd.conf /etc/sockd.conf.orig
    
  - name: create new sockd.conf
    template: src=templates/sockd.conf.j2 dest=/etc/sockd.conf mode=0755
    
  - name: Add new user without shell login
    user:
      name: proxyuser
      shell: /usr/sbin/nologin
      password: "{{ proxyuserpassword|password_hash('sha512') }}"

  - name: Start Proxy server and enable on boot
    service: name=sockd state=started enabled=yes
  - service: name=sockd state=restarted

  - name: Enable EPEL Repository
    yum:
      name: epel-release
      state: latest
      
  - name: Install fail2ban
    yum: >
      name=fail2ban
      state=latest
      
  - name: Enable fail2ban service
    systemd:
      name: fail2ban
      enabled: yes
      state: started
      
  - name: create jail.local
    template: src=templates/jail.local.j2 dest=/etc/fail2ban/jail.local mode=0755
    
  - name: restart fail2ban
    systemd:
      name: fail2ban
      state: restarted
      
  - name: Add Zabbix repository
    command: rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    
  - name: Install Zabbix-Agent
    yum: >
      name=zabbix-agent
      state=latest
      
  - name: Remove Config-File
    file: >
      path=/etc/zabbix/zabbix_agentd.conf 
      state=absent
      
  - name: Create new agent config file
    template: src=templates/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf mode=0755
    
  - name: Restart zabbix-agent
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes

  - name: Install Repository OpenVpn
    yum: >
      name=https://as-repository.openvpn.net/as-repo-centos7.rpm
      state=present
      
  - name: Install OpenVpn Server
    yum: >
      name=openvpn-as
      state=latest
      
  - name: Change User password
    user:
      name: openvpn
      update_password: always
      password: "{{ openvpnpassword|password_hash('sha512') }}"
      
  - name: Restart openvpn-server
    systemd:
      name: openvpnas
      state: restarted
      enabled: yes
      
  - name: add firewalld rich-rules
    firewalld:
        rich_rule: 'rule family="ipv4" source address=192.168.1.115 accept'
        zone: public
        immediate: yes
        permanent: true
        state: enabled

  - firewalld:
        rich_rule: 'rule family="ipv4" source address=192.168.2.0/24 accept' 
        zone: public
        immediate: yes
        permanent: true
        state: enabled

  - firewalld:
        rich_rule: 'rule family="ipv4" source address=192.168.3.0/24 accept' 
        zone: public
        immediate: yes
        permanent: true
        state: enabled

  - name: remove dhcp6 and ssh rules and set target to zone DROP
    command: firewall-cmd --zone=public --permanent --remove-service=dhcpv6-client
  - command: firewall-cmd --zone=public --permanent --remove-service=ssh
  - command: firewall-cmd --set-target=DROP --zone=public --permanent
  - command: firewall-cmd --reload  
   
  - name: systemctl daemon-reexec
    systemd: daemon_reexec=yes
