---
- name: Super Playbook
  hosts: test
  become: yes

  vars:
    mytext: "Hello from WKD"

  tasks:
  - name: Ping test
    ping

  - name: Create folder_first
    file:
      path: /home/secret/folder_first
      state: directory
      mode: 0755

  - name: Create folder_second
    file:
      path: /home/secret/folder_second
      state: directory
      mode: 0755

  - name: Create file_first
    copy:
      dest: /home/secret/file_first.txt
      content: |
        Text Line first, in file_first
        Text Line second, in file_first
        Text Line third, {{ mytext }}

  - name: Create file_second
    copy:
      dest: /home/secret/file_second.txt
      content: |
        Text Line first, in file_second
        Text Line second, in file_second
        Text Line third, {{ mytext }}
