---
- name: Testing Import and Include
  hosts: test
  become: yes

  vars:
    mytext: "Hello from WKD"

  tasks:

  - name: Ping test
    ping

  - include: create_folders.yml
  - include: create_files.yml  mytext="WKD is here!"
