# This is a basic workflow to help you get started with Actions

name: CI_checking


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello World from Testing Job"
      
      - name: FULL CLONNING OF REPOSITORY
        uses: actions/checkout@v1    
      - name: List current folder
        run: ls -la
        
  
